theme: jekyll-theme-minimal
title: SYSTEM OPERATOR PORTFOLIO
description: Industrial Automation | Software Infrastructure | Alternative Marketstheme: jekyll-theme-minimal
title: SYSTEM OPERATOR PORTFOLIO
description: Industrial Automation | Software Infrastructure | Alternative Markets
